<a href="https://colab.research.google.com/github/Shravani703/HappyDB/blob/master/Class_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# BUS AN 511: Programming Essentials  
# Class 1 Python Basics  
**Mingwen Yang**, University of Washington

## 1. Print Statement and Comments
You can execute a code by pressing "Shift + Enter". 

In [ ]:
print('Hello World!')

**Comments**  
- Code cell vs Markdown cell in google collab
- Inside a "code" cell, any text following # (hash or pound sign) is ignored by the Python interpreter
- Useful to make notes, explain code, or simply comment out code that you don't want to delete.
- In a Jupyter Notebook, however, you may prefer to document comments in a "Markdown" cell as you can better format your comments.

In [ ]:
print("Hello World!") # double quotes do not do anything fancy 

## 2. Scalar Data Types
Python has a small set of built-in types to handle numerical data, strings, boolean (True or False) values, etc.  
These are called scalar types or scalars.  
A scalar is a type that can have a single value such as 2, 7.14, or "Anne".  
The commonly used scalar types in Python:  
  - int (integer): a number without a fractional part. 
  - float (floating point number): a number that has both an integer and fractional part, separated by a point. 
  - bool (True or False value): a type to represent logical values. Can only be True or False.  
  - str (String): a type to represent text. You can use single or double quotes to build a string.
  - Single dimension data types, what is a non scalar data type?

In [ ]:
type(5)

int

In [ ]:
type(1.75)

float

In [ ]:
type("Hello") #quote needed for string types

str

In [ ]:
type(True)

bool

### 2.1 String  
Strings in Python are identified as a set of characters represented in the quotation marks. Python allows for either pairs of single or double quotes. Subsets of strings can be taken using the slice operator with indexes starting at 0 in the beginning of the string and working their way from -1 at the end.  
The plus (+) sign is the string concatenation operator and the asterisk (*) is the repetition operator.

In [ ]:
str1 = "Hello World!"

print(str1) # Print complete string
print(str1[0]) # Print first character of the string | indexing starts from 0
print(str1[2:5]) # Print characters starting from 3rd to 5th | includes the first index, excludes the last index
print(str1[2:]) # Print string starting from 3rd character

print(str1 * 2) # Print string two times
print(str1 + "TEST") # Print concatenated string

Hello World!
H
llo
llo World!
Hello World!Hello World!
Hello World!TEST


In [ ]:
str2 = str1.upper()
print(str2)

HELLO WORLD!


In [ ]:
str3 = str2.lower()  
print(str3)  #unrelated note: variable names are case sensitive

hello world!


## 3. Variables 
Variables indicate stored information in the computer's memory.  
- You can create a new variable and assign a value to it using assignment statements. e.g., x = 5
- The = symbol is called the assignment operator and notifies Python to store the data on the right side of the statement into the variable name printed on the left side (i.e., x).
- When assigning a variable in Python, you are actually creating a reference to the object in the right hand side of the equal sign
- Assignments are **unidirectional** in Python.
- Variable names are **case sensitive**.
- Variable names can begin with an _ (underscore) or a letter, not a number.
- Python's keywords cannot be used as variable names

**Python Keywords**  

False	await	else	import	pass  
None	break	except	in	raise  
True	class	finally	is	return  
and	continue	for	lambda	try  
as	def	from	nonlocal	while  
assert	del	global	not	with  
async	elif	if	or	yield  

In [ ]:
counter = 100 # an integer assignment 
miles = 59.7 # a floating point
name = "Wendy" # a string 

print(counter)
print(miles)
print(name)

100
59.7
Wendy


In [ ]:
# why does the following code not work?  
my_variable = 10
print(my_varable) #NameError, the variable name is not defined

NameError: ignored

In [ ]:
# assignments is unidirectional in Python
variable1=27
print(variable1)

27


In [ ]:
# why does the following code not work?
27=variable1 # This will cause error; assignments are unidirectional

In [ ]:
# why does the following code not work?
1variable = 35 #variable name starts with a number

In [ ]:
a = 3
print(a)
a = "John"
print(a) # flexibility of python, it is not tied to the original data type - it will replace the data in the variable

3
John


## 4. Arithmetic and Logical Operators  
Most of the binary math operations and comparisons are as you might expect.
It is a good practice to surround the following binary operators with a single space on either side:

- assignment (=)
- comparisons (==, <, >, !=, <=, >=, in, not in, is, is not)
- Booleans (and, or, not)

Pay attention to priority of operators.

In [ ]:
2+1

3

In [ ]:
2**3 # exponentiation, 2 raised to the third power

8

In [ ]:
3/10

0.3

In [ ]:
10//3 # floor divide 10 by 3, dropping any fractional remainder

3

In [ ]:
10%3 # modulo operator yields the remainder after division

1

In [ ]:
2 + 3*4

14

In [ ]:
(2+3) * 4

20

### 4.1 Boolean Logic   
There are two boolean values: True and False.   
True and False can be assigned to variables just like strings or numbers.   
Logical operators for boolean values: == (exactly equal to), != (not equal to), > (greater than), >= (greater than or equal to), and, or, not   

In [ ]:
a = 2
b = 3
a == b # equal vs assignment operator | sql selection runs on boolean logic SELECT WHERE

False

In [ ]:
a != b

True

In [ ]:
a>1 and b>1 # both conditions must be satisfied 

True

In [ ]:
a>1 and b>8

False

In [ ]:
a>1 or b>8

True

## 5. Import Packages or Libraries
For example, you may want to calculate the area of a circle. When the radius is r, the area is $A = \pi r^2$. To use the constant $\pi$, you’ll need the math package. **most open source software has packages**

In [ ]:
# radius
r = 0.3
import math # Import the math package.
# Now you can access the constant pi with math.pi
A = math.pi *r *r
print(A)

0.2827433388230814


In [ ]:
import keyword
keyword.kwlist # we are using the kwlist function of the keyword module
# These are all the in-built keywords
# a package to simply let you know of all the reserved words in python

['False',
 'None',
 'True',
 'and',
 'as',
 'assert',
 'async',
 'await',
 'break',
 'class',
 'continue',
 'def',
 'del',
 'elif',
 'else',
 'except',
 'finally',
 'for',
 'from',
 'global',
 'if',
 'import',
 'in',
 'is',
 'lambda',
 'nonlocal',
 'not',
 'or',
 'pass',
 'raise',
 'return',
 'try',
 'while',
 'with',
 'yield']

### 5.1 Selective import  
General imports, like import math, make all functionality from the math package available to you. However, if you decide to only use a specific part of a package, you can always make your import more selective.

In [ ]:
from math import pi
r = 0.3
A = pi *r *r # here we can directly use pi as opposed to math.pi
print(A)

### 5.2 Another example 

In [ ]:
numbers = [1,2,3,4,5] # a list of numbers
numbers

[1, 2, 3, 4, 5]

In [ ]:
import statistics

mean = statistics.mean(numbers)
print(mean)

3


In [ ]:
import statistics as s #create a nick name for your package

mean = s.mean(numbers)
print(mean)

3


In [ ]:
from statistics import mean

mean = mean(numbers)
print(mean)

3


In [ ]:
from statistics import mean as m
mean = m(numbers)
print(mean)

3


In [ ]:
from statistics import mean as m, median as med
mean = m(numbers)
median = med(numbers)
print(mean)
print(median)

3
3


### 5.3 In-class exercise 
Selectively import the square root function sqrt from math package. Then compute the square
root of 10.

In [ ]:
from math import sqrt
square_root=sqrt(10)
print(square_root)

3.1622776601683795


## 6. List 
Lists are the most versatile of Python’s compound data types. A list contains items separated by commas and enclosed within square brackets ([]).  
The values stored in a list can be accessed using the slice operator ([ ] and [:]) with indexes starting at 0 in the beginning of the list and working their way to end -1.   
The plus (+) sign is the list concatenation operator, and the asterisk (*) is the repetition operator. 

In [ ]:
# A list is a compound data type, you can group values together | non scalar data type | diff elements of list can be diff data types
a = 10
my_list = [ a, 'abcd', 786 , 2.23, 'john']
print(my_list)

[10, 'abcd', 786, 2.23, 'john']


In [ ]:
tinylist = [123, 'john']
print(tinylist * 2) # Prints list two times
print(my_list + tinylist) # Prints concatenated lists - combine 2 lists

[123, 'john', 123, 'john']
[10, 'abcd', 786, 2.23, 'john', 123, 'john']


### 6.1 Indexing and Slicing

In [ ]:
print(my_list) # Print complete list
print(my_list[0]) # Print first element of the list | indexing starts at 0
print(my_list[1:3]) # Print elements starting from 2nd till 3rd | includes starting index, excludes ending index
print(my_list[2:]) # Print elements starting from 3rd element
print(my_list[-1]) # Print the last element | counting from the back from -1

[10, 'abcd', 786, 2.23, 'john']
10
['abcd', 786]
[786, 2.23, 'john']
john


In [ ]:
# Variables can also be used as indexing
myStart = 2
print(my_list[myStart])
# get the length of a list
len(my_list)

786


5

### 6.2 List Manipulation
Replacing list elements is pretty easy. Simply subset the list and assign new values to the subset. You can select single elements or you can change entire list slices at once.

In [ ]:
x = ['a', 'b', 'c', 'd']
x[1] = 'r' # replace an element
print(x)
x[2:] = ['s', 't']
print(x)

['a', 'r', 'c', 'd']
['a', 'r', 's', 't']


Extend a list with the + operator. Add new elements into a list.

In [ ]:
x = ['a', 'b', 'c', 'd']
y = x + ['e', 'f']
print(y)

['a', 'b', 'c', 'd', 'e', 'f']


Delete list elements with del statement.

In [ ]:
x = ['a', 'b', 'c', 'd']
del(x[1])
print(x)

['a', 'c', 'd']


### 6.3 In-class exercise 
The following list, areas, that contains the area of the hallway, kitchen, living room, bedroom and
bathroom, in this order.   
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
- Use slicing to create a list, downstairs, that contains the first 6 elements of areas.
- Do a similar thing to create a new variable, upstairs, that contains the last 4 elements of areas.
- Print both downstairs and upstairs

In [ ]:
areas = ["hallway", 11.25, "kitchen", 18.0, "living room", 20.0, "bedroom", 10.75, "bathroom", 9.50]
downstairs=areas[:6]
upstairs1=areas[-4:]
upstairs2=areas[6:]
print(downstairs)
print(upstairs1)
print(upstairs2)

['hallway', 11.25, 'kitchen', 18.0, 'living room', 20.0]
['bedroom', 10.75, 'bathroom', 9.5]
['bedroom', 10.75, 'bathroom', 9.5]


## 7. Numpy  
Numpy (Numeric Python) is the fundamental package for data science and scientific computing with Python.

In [ ]:
# the list length represents the length of some rectangles
# the list width represents the width of some rectangles
length = [2, 4, 6, 8]
width = [1.4, 3.2, 1, 6]
# we want to calculate area of the rectangles
length * width # it can't do a one to one mapping between the lists | Type error
# or double the length of every rectangle
length * 2

TypeError: ignored

**What are the properties of numpy arrays?**

Numpy array is an alternative to Python list. It makes calculations over the entire arrays. 

In [ ]:
import numpy as np # you can now refer to numpy as np 
# use np.array() to create a numpy array from length.
np_length = np.array(length) # np.array is a function to do the type conversion | you can convert the list to a numpy array
print(np_length)

[2 4 6 8]


In [ ]:
# Math on numpy arrays
print(np_length+1)
print(np_length*2)
print(np_length + np_length)

In [ ]:
np_width = np.array(width)
print(np_width)

In [ ]:
print(np_length*np_width)

### 7.1 In-class exercise 
The list baseball_h represents the height of some baseball players in inches.   
baseball_h = [72,78, 69,71,76, 79]  
Let’s first convert all height measurements from inches to meters. Multiply by 0.0254 to go from inches to meters.
Store the new values in a new array, height_m. Print out height_m and check if the output makes sense.

We also have the weight (in pounds) of each baseball player as follows:  
baseball_w = [180, 215, 210, 188, 176, 209]  
Multiply by 0.453592 to go from pounds to kilograms. Store the resulting numpy array as weight_kg.  

Use height_m and weight_kg to calculate the BMI of each player as follows:  
$BMI = \frac{weight(kg)}{height(m)*height(m)}$ 
Save the resulting numpy array as bmi and print out the values. 

In [ ]:
baseball_h = [72,78, 69,71,76, 79]

import numpy as np
baseball_m=np.array(baseball_h)
baseball_m=baseball_m*0.0254
print(baseball_m)

baseball_w = [180, 215, 210, 188, 176, 209]  
baseball_p=np.array(baseball_w)
baseball_p=baseball_p*0.453592
print(baseball_p)

BMI = baseball_p/(baseball_m**2)
print(BMI)


[1.8288 1.9812 1.7526 1.8034 1.9304 2.0066]
[81.64656  97.52228  95.25432  85.275296 79.832192 94.800728]
[24.41211827 24.84546948 31.01123531 26.22038745 21.42315531 23.54453169]


### 7.2 Numpy array indexing and slicing 
To subset both regular Python lists and numpy arrays, we can use the square brackets.

In [ ]:
x = [4 , 9 , 6, 3, 1]
print(x[1])
y = np.array(x)
print(y[1])
print(y[1:3])
print(y[3:])
print(y[-2])

9
9
[9 6]
[3 1]
3


For numpy only, we can also use a list of integers to select positions.

In [ ]:
print(y) # print the entire numpy array
sub_y = y[[0,4,2]] # get a subset of the numpy array and assign it to sub_y | choose the 1st, 5th, 3rd element
print(sub_y) # print the subset

# compare with list
print(x)
x = x[[0,4,2]] # wrong syntex

[4 9 6 3 1]
[4 1 6]
[4, 9, 6, 3, 1]


TypeError: ignored

### 7.3 Comparing Numpy with basic Python lists
Numpy is great for doing vector arithmetic. If you compare its functionality with regular Python lists, however, some things have changed.  
- Numpy arrays cannot contain elements with different types. If you try to build such a list, some of the elements' types are changed to end up with a homogeneous list.
- The typical arithmetic operators, such as + and * have a different meaning for regular Python lists and numpy arrays.

### 7.4 2D numpy arrays 
Now let’s construct our first 2D array.

In [ ]:
list_2d = [[72,78, 69,71,76, 79],[180, 215, 210, 188, 176, 209]]
np_2d = np.array(list_2d)
np_2d

array([[ 72,  78,  69,  71,  76,  79],
       [180, 215, 210, 188, 176, 209]])

In [ ]:
np_2d.shape # 2 rows, 6 columns

(2, 6)

In [ ]:
# Indexing and Slicing 
print(np_2d[0]) # first row
print(np_2d[0][2]) # first row, third column
print(np_2d[0,2]) # Alternative slicing

[72 78 69 71 76 79]
69
69


In [ ]:
np_2d[:,2:4] # : stands for all the rows

array([[ 69,  71],
       [210, 188]])

In [ ]:
np_2d[0,:]

array([72, 78, 69, 71, 76, 79])

## 8. User Input

In [ ]:
input("Enter a number:")

Enter a number:4


'4'

In [ ]:
x = input("Enter a number:") # input default is always a string

Enter a number:4


In [ ]:
print(x)
type(x)

4


str

In [ ]:
x = int(x)
type(x) #if you convert a value from float to integer the value will be different

int

## 9. Random Number

In [ ]:
import random
# generate a number between 0 and 1
rv = random.uniform(0, 1)
print (rv)

An array of random Gaussian values can be generated using the randn() NumPy function.  
This function takes a single argument to specify the size of the resulting array. The Gaussian values are drawn from a standard Gaussian distribution; this is a distribution that has a mean of 0.0 and a standard deviation of 1.0.


*   Random numner important for random sampling and A/B testing - control group

*   Normal and gaussian are the same, what does it mean to draw a random variable that follows a normal distribution?

* Randomizing the data is important once you have analyzed it for data privacy - grouping very detailed data or they would add some noise to the data - this noise is a random variable with mean and SD following normal distribution
*  Seed - a way to replicate the random variables - i want to make sure that every time I run this code on my computer, you will generate the same set of random variables. You keep changing the value of the seed to create a new set.



experimental group

In [ ]:
# generate random Gaussian values
from numpy.random import seed
from numpy.random import randn
# seed random number generator
seed(1)
# generate some Gaussian values
values = randn(10)
print(values)